---
- hosts: all
  become: true

  tasks:
    - name: Print some debug information 
      vars: 
          # Environment Variables ("environment"):
          # --------------------------------
          # {{ environment | to_nice_json }} 
          
          # GROUP NAMES Variables ("group_names"):
          # --------------------------------
          # {{ group_names | to_nice_json }}
          
          # GROUPS Variables ("groups"):
          # --------------------------------
          # {{ groups | to_nice_json }}
          
          # Module Variables ("vars"):
          # --------------------------------
          # {{ vars | to_nice_json }} 

        msg: |
          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }} 
          
    
      debug: 
        msg: "{{ msg.split('\n') }}"      

    - name: show all the hosts matching the pattern
      debug:
        msg: "{{ item }}"
      with_inventory_hostnames:
        - all
        
    - name: AAAAAAAAAAAAAAAAAA
      ansible.builtin.copy:
        dest: "/etc/korp/test.txt"
        mode: '0644'
        content: "test 1"

    - name: BBBBBBBBBBBBBBBBB
      ansible.builtin.copy:
        dest: "/etc/korp/test1.txt"
        mode: '0644'
        content: "{{ test_var }}"
