---
- hosts: all
  become: true

  tasks:

    - name: show all the hosts matching the pattern
      debug:
        msg: "{{ item }}"
      with_inventory_hostnames:
        - all
        
    - name: AAAAAAAAAAAAAAAAAA
      ansible.builtin.copy:
        dest: "/etc/korp/test.txt"
        mode: '0644'
        content: "test 1"

    - name: BBBBBBBBBBBBBBBBB
      ansible.builtin.copy:
        dest: "/etc/korp/test1.txt"
        mode: '0644'
        content: "{{ test_var }}"
