---
- hosts: all
  become: true
  vars:
    vg_korp_name: vg_korp
    lv_korp_name: lv_korp
    free_disks: []
    korp_disk: ""

  # criação de LVM:
  #   https://www.linuxbuzz.com/create-lvm-partition-in-linux/
  # remoção de LVM:
  #   https://www.looklinux.com/how-to-remove-volume-group-and-physical-volume-on-lvm/

  tasks:
    - debug:
        msg: 
          - "{{ var_2 }}"
          - "{{ cert_crt_path }}"