services:
  Viasoft.Logistics.PreRegistration:
    version: 3.0.x
    db:
      name: Viasoft_Logistics_PreRegistration
      type: mssql
  
  Viasoft.Logistics.PreRegistration-frontend:
    front_name: LOG00
    version: 3.1.x
