- name: Definição de variáveis
  ansible.builtin.set_fact:
    services: "{{ (lookup('ansible.builtin.template', 'vars/main.yml') | from_yaml)['services'] }}"

- name: Adição de serviços de ERP
  ansible.builtin.include_role:
    name: utils
    tasks_from: services/add_service
  vars:
    service_name: "{{ item.key }}"
    id: ERP
  with_dict: "{{ services }}"
  loop_control:
    extended: true

- name: "Garantia de kv no consul para Viasoft.ELT"
  ansible.builtin.include_role:
    name: utils
    tasks_from: 'consul_kv/ensure_kv'
  vars:
    service_name: Viasoft.ELT
